# -*- coding: utf-8 -*-
"""Chapter_3_RBS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Tomileee0300/MachineLearningProject/blob/main/Chapter_3_RBS.ipynb
"""

# ======================================================
# FAKE vs GENUINE NAIRA NOTE CLASSIFICATION
# Dataset source:
# https://github.com/Oyibo-Efetobor/fake_naira_detection
#
# Train:
#   - train/fake
#   - train/genuine
#
# Test:
#   - Remaining images (unseen)
#
# Model: MobileNetV2
# Evaluation: Accuracy, Confusion Matrix, Classification Report
# ======================================================

# -----------------------------
# 1. Install dependencies
# -----------------------------
!pip install -q tensorflow matplotlib seaborn opencv-python scikit-learn

import os
import shutil
import random
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import classification_report, confusion_matrix

print("✅ Libraries installed")

# -----------------------------
# 2. Clone GitHub repository
# -----------------------------
!rm -rf fake_naira_detection
!git clone https://github.com/Oyibo-Efetobor/fake_naira_detection.git

print("✅ Repository cloned")

# -----------------------------
# 3. Define paths
# -----------------------------
repo_root = Path("/content/fake_naira_detection")

train_fake_src = repo_root / "train/fake"
train_genuine_src = repo_root / "train/genuine"

# Create clean dataset structure
dataset_root = Path("/content/naira_dataset")

train_fake = dataset_root / "train/fake"
train_genuine = dataset_root / "train/genuine"
test_fake = dataset_root / "test/fake"
test_genuine = dataset_root / "test/genuine"

# Clean previous dataset
if dataset_root.exists():
    shutil.rmtree(dataset_root)

for folder in [train_fake, train_genuine, test_fake, test_genuine]:
    folder.mkdir(parents=True, exist_ok=True)

# -----------------------------
# 4. Helper functions
# -----------------------------
def get_images(folder):
    imgs = []
    for ext in ["*.jpg", "*.jpeg", "*.png", "*.webp"]:
        imgs.extend(folder.rglob(ext))
    return imgs

def split_train_test(images, train_folder, test_folder, ratio=0.8):
    random.shuffle(images)
    split_idx = int(len(images) * ratio)
    train_imgs = images[:split_idx]
    test_imgs = images[split_idx:]

    for img in train_imgs:
        shutil.copy(img, train_folder / img.name)
    for img in test_imgs:
        shutil.copy(img, test_folder / img.name)

    return len(train_imgs), len(test_imgs)

random.seed(42)

# -----------------------------
# 5. Prepare datasets
# -----------------------------
fake_images = get_images(train_fake_src)
genuine_images = get_images(train_genuine_src)

print(f"Fake images found: {len(fake_images)}")
print(f"Genuine images found: {len(genuine_images)}")

fake_train_count, fake_test_count = split_train_test(
    fake_images, train_fake, test_fake
)

genuine_train_count, genuine_test_count = split_train_test(
    genuine_images, train_genuine, test_genuine
)

print("\n✅ Dataset prepared")
print(f"Fake → {fake_train_count} train | {fake_test_count} test")
print(f"Genuine → {genuine_train_count} train | {genuine_test_count} test")

# -----------------------------
# 6. Data generators
# -----------------------------
IMG_SIZE = 224
BATCH_SIZE = 16

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    dataset_root / "train",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

test_gen = test_datagen.flow_from_directory(
    dataset_root / "test",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False
)

print("Class mapping:", train_gen.class_indices)
# Expected: {'fake': 0, 'genuine': 1}

# -----------------------------
# 7. Build model (MobileNetV2)
# -----------------------------
base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
x = Dense(128, activation="relu")(x)
x = Dropout(0.3)(x)
output = Dense(1, activation="sigmoid")(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# -----------------------------
# 8. Train model
# -----------------------------
EPOCHS = 10

history = model.fit(
    train_gen,
    validation_data=test_gen,
    epochs=EPOCHS
)

# -----------------------------
# 9. Evaluate model
# -----------------------------
print("\n✅ Evaluating model on TEST data")

test_gen.reset()
pred_probs = model.predict(test_gen)
preds = (pred_probs > 0.5).astype(int).flatten()

true_labels = test_gen.classes
class_names = list(test_gen.class_indices.keys())

print("\nClassification Report:")
print(classification_report(true_labels, preds, target_names=class_names))

# Confusion Matrix
cm = confusion_matrix(true_labels, preds)

plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix – Fake vs Genuine Naira Notes")
plt.show()

# -----------------------------
# 10. Save model
# -----------------------------
model.save("naira_fake_vs_genuine_model.h5")
print("✅ Model saved as naira_fake_vs_genuine_model.h5")

# ============================================================
# COMPLETE FAKE vs GENUINE NAIRA NOTE CLASSIFICATION PIPELINE
# Dataset: https://github.com/Oyibo-Efetobor/fake_naira_detection
# Includes:
# - Training
# - Fine-tuning
# - Evaluation (Confusion Matrix, ROC, AUC)
# - Image testing
# - Camera detection code
# ============================================================

# ----------------------------
# 1. Install dependencies
# ----------------------------
!pip install -q tensorflow matplotlib seaborn opencv-python scikit-learn

import os, shutil, random
from pathlib import Path
import numpy as np
import cv2
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    auc
)

print("✅ Libraries ready")

# ----------------------------
# 2. Clone GitHub dataset
# ----------------------------
!rm -rf fake_naira_detection
!git clone https://github.com/Oyibo-Efetobor/fake_naira_detection.git

repo_root = Path("/content/fake_naira_detection")

# ----------------------------
# 3. Prepare TRAIN / TEST sets
# ----------------------------
dataset_root = Path("/content/naira_dataset")
train_fake = dataset_root / "train/fake"
train_genuine = dataset_root / "train/genuine"
test_fake = dataset_root / "test/fake"
test_genuine = dataset_root / "test/genuine"

if dataset_root.exists():
    shutil.rmtree(dataset_root)

for f in [train_fake, train_genuine, test_fake, test_genuine]:
    f.mkdir(parents=True, exist_ok=True)

def get_images(folder):
    imgs = []
    for ext in ["*.jpg","*.jpeg","*.png","*.webp"]:
        imgs.extend(folder.rglob(ext))
    return imgs

def split(images, train_dir, test_dir, ratio=0.8):
    random.shuffle(images)
    k = int(len(images)*ratio)
    for img in images[:k]:
        shutil.copy(img, train_dir / img.name)
    for img in images[k:]:
        shutil.copy(img, test_dir / img.name)

random.seed(42)

split(get_images(repo_root/"train/fake"), train_fake, test_fake)
split(get_images(repo_root/"train/genuine"), train_genuine, test_genuine)

print("✅ Dataset prepared")

# ----------------------------
# 4. Data generators
# ----------------------------
IMG_SIZE = 224
BATCH_SIZE = 16

train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1
).flow_from_directory(
    dataset_root/"train",
    target_size=(IMG_SIZE,IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

test_gen = ImageDataGenerator(
    rescale=1./255
).flow_from_directory(
    dataset_root/"test",
    target_size=(IMG_SIZE,IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False
)

print("Class mapping:", train_gen.class_indices)

# ----------------------------
# 5. Build model (MobileNetV2)
# ----------------------------
base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE,IMG_SIZE,3)
)
base_model.trainable = False

x = GlobalAveragePooling2D()(base_model.output)
x = Dropout(0.3)(x)
x = Dense(128, activation="relu")(x)
output = Dense(1, activation="sigmoid")(x)

model = Model(base_model.input, output)
model.compile(
    optimizer=Adam(1e-4),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# ----------------------------
# 6. Train (Phase 1)
# ----------------------------
print("🚀 Training Phase 1")
model.fit(train_gen, epochs=8, validation_data=test_gen)

# ----------------------------
# 7. Fine-tuning (Phase 2)
# ----------------------------
print("🔥 Fine-tuning Phase 2")

base_model.trainable = True
for layer in base_model.layers[:-40]:
    layer.trainable = False

model.compile(
    optimizer=Adam(1e-5),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.fit(train_gen, epochs=8, validation_data=test_gen)

# ----------------------------
# 8. Evaluation
# ----------------------------
test_gen.reset()
y_prob = model.predict(test_gen).ravel()
y_pred = (y_prob > 0.5).astype(int)
y_true = test_gen.classes

print("\n📊 Classification Report")
print(classification_report(y_true, y_pred, target_names=["Fake","Genuine"]))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Fake","Genuine"],
            yticklabels=["Fake","Genuine"])
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ROC + AUC
fpr, tpr, _ = roc_curve(y_true, y_prob)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

# ----------------------------
# 9. Save model
# ----------------------------
model.save("naira_fake_detector_final.h5")
print("✅ Model saved as naira_fake_detector_final.h5")

# ----------------------------
# 10. TEST IMAGE IN COLAB
# ----------------------------
from google.colab import files
uploaded = files.upload()
img_path = list(uploaded.keys())[0]

img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img_resized = cv2.resize(img, (IMG_SIZE,IMG_SIZE))/255.0

pred = model.predict(np.expand_dims(img_resized,0))[0][0]

plt.imshow(img)
plt.axis("off")
print("GENUINE" if pred>0.5 else "FAKE", "| Confidence:", round(pred if pred>0.5 else 1-pred,2))

# ----------------------------
# 11. CAMERA DETECTION CODE (LOCAL LAPTOP)
# ----------------------------
print("""
===========================================
LOCAL CAMERA CODE (RUN ON YOUR LAPTOP)
===========================================

import cv2, numpy as np, tensorflow as tf

model = tf.keras.models.load_model("naira_fake_detector_final.h5")
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    img = cv2.resize(frame,(224,224))/255.0
    pred = model.predict(np.expand_dims(img,0))[0][0]
    label = "GENUINE" if pred>0.5 else "FAKE"
    cv2.putText(frame,label,(20,40),
                cv2.FONT_HERSHEY_SIMPLEX,1,
                (0,255,0) if label=="GENUINE" else (0,0,255),2)
    cv2.imshow("Naira Detector",frame)
    if cv2.waitKey(1)&0xFF==ord('q'): break

cap.release()
cv2.destroyAllWindows()
""")